---
abstract: "Log to Test::More's diagnostic output"
author:
  - 'Graham TerMarsch (cpan@howlingfrog.com)'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-TestDiag
provides:
  Log::Dispatch::TestDiag:
    file: lib/Log/Dispatch/TestDiag.pm
    version: 0.01
requires:
  Log::Dispatch::Output: 0
  Test::More: 0
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: 0.01
